version: '3'
services:

  transcribator_whisper:
    container_name: transcribator_whisper
    image: fedirz/faster-whisper-server:latest-cpu
    restart: always
    networks:
      app_net_3:
        ipv4_address: 10.0.2.2
    ports:
      - "8000:8000"
    volumes:
      - cache_transcribator:/root/.cache/huggingface

  transcribator_nginx:
    container_name: transcribator_nginx
    image: nginx:1.21.3-alpine
    depends_on:
      - transcribator_whisper
    restart: always
    env_file:
      - ../.env
    networks:
      app_net_3:
        ipv4_address: 10.0.2.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: service nginx status || exit 1
      interval: 70s
      timeout: 3s
      retries: 3
      start_period: 30s

  transcribator_bot:
    container_name: transcribator_bot
    build:
      context: ../bot/
      dockerfile: Dockerfile_bot
    depends_on:
      - spektr_nginx
    restart: always
    env_file:
      - ../.env
    networks:
      app_net_2:
        ipv4_address: 10.0.2.4
    volumes:
      - logs_transcribator:/app/logs/

volumes:
  cache_transcribator:
  logs_transcribator:

networks:
  app_net_3:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
